CREATE TABLE "portfolio_items" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "format" TEXT NOT NULL,
    "image_url" TEXT NOT NULL,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "portfolio_items_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "portfolio_items_slug_key" ON "portfolio_items"("slug");

INSERT INTO "portfolio_items" ("id", "slug", "title", "category", "summary", "format", "image_url", "featured", "sort_order") VALUES
('project-01', 'photo-2', 'photo 2', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/2.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8yLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg1OTMsImV4cCI6MTgxMzA2NDU5M30.R3id-vHTwXjFZr7gY8ALEcCsIcyInH5c3gPY-eJtsrs', true, 1),
('project-02', 'photo-3', 'photo 3', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/3.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8zLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg4MjYsImV4cCI6MTgxMzA2NDgyNn0.0lZruI-4J7XZI8Ff8WxnLXsnMsm34HQQi2emkshea5k', false, 2),
('project-03', 'photo-4', 'photo 4', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/4.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy80LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg4NDMsImV4cCI6MTgxMzA2NDg0M30.fKmE5lNVRraTR3pDP0GXxZ5QMrdeqqbHXwrUFb2PFl8', false, 3),
('project-04', 'photo-5', 'photo 5', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/5.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy81LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg4NTMsImV4cCI6MTgxMzA2NDg1M30.d7kkwNpwTA16Fnt40YTt8PQOVQIEx2-NuJwNCAATV3M', false, 4),
('project-05', 'photo-6', 'photo 6', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/6.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy82LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg4NjMsImV4cCI6MTgxMzA2NDg2M30.mk_4LVC_sslfZJuwfBZzTa76TlLnYU3_z6l1LMGV1JQ', false, 5),
('project-06', 'photo-7', 'photo 7', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/7.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy83LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg5MjAsImV4cCI6MTgxMzA2NDkyMH0.ODhoKNwruLLqw4JOxFMTGxNl1y8bJn1_Q2oSLCzo1hA', false, 6),
('project-07', 'photo-8', 'photo 8', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/8.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy84LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg5MjksImV4cCI6MTgxMzA2NDkyOX0.r3bnPi9Dz3-ntg5-alWXQgQ47L0FC0aIij7KbPRSXrg', false, 7),
('project-08', 'photo-9', 'photo 9', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/9.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy85LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODE1Mjg5NDYsImV4cCI6MTgxMzA2NDk0Nn0.KLITsDP4Pj-ppsO5LGjIxcK-mv0hhSdA9VxM7Ak14Lw', false, 8),
('project-09', 'photo-10', 'photo 10', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/10.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xMC5qcGciLCJzY29wZSI6ImRvd25sb2FkIiwiaWF0IjoxNzgxNTI4NjE2LCJleHAiOjE4MTMwNjQ2MTZ9.A3vqqn_up1L0Glk5GwYvoWPy3uFNqMbmE11WmgL8CWs', false, 9),
('project-10', 'photo-11', 'photo 11', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/11.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xMS5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODY0NCwiZXhwIjoxODEzMDY0NjQ0fQ.AYKa3mFi4RZSv_OPiQe9ToRq8QscEB6C5BzP9UdlAQI', false, 10),
('project-11', 'photo-12', 'photo 12', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/12.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xMi5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODY3NywiZXhwIjoxODEzMDY0Njc3fQ.ij_z-Vo98JLnsXzl2QkIZr4RtLpPkKgRxT_YvOJN_Fw', false, 11),
('project-12', 'photo-13', 'photo 13', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/13.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xMy5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODY5NSwiZXhwIjoxODEzMDY0Njk1fQ.mzy9V2y-c1E02JA06tOdsTHdsSNMxX5toFdMHZ6Y51w', false, 12),
('project-13', 'photo-14', 'photo 14', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/14.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xNC5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODcwNywiZXhwIjoxODEzMDY0NzA3fQ.uNNsM45rJwUj0ylx3a7Xx7QYYKomqXugIAH3SQu6mok', false, 13),
('project-14', 'photo-15', 'photo 15', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/15.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xNS5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODcyMCwiZXhwIjoxODEzMDY0NzIwfQ.nAfHjKSHRHdgJy6fjFtrf64SEguN7zIrrogmnYcol4E', false, 14),
('project-15', 'photo-16', 'photo 16', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/16.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xNi5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODcyOCwiZXhwIjoxODEzMDY0NzI4fQ.HbTshxN6JLuiJuK5VpjgeqxGRSpW3WG1dEB7uiK_BTE', false, 15),
('project-16', 'photo-17', 'photo 17', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/17.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xNy5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODc0MCwiZXhwIjoxODEzMDY0NzQwfQ.Wzw9mI0FtbSs5j1r-5bDYuhEh-IXCTA0DkApfIl1NkA', false, 16),
('project-17', 'photo-18', 'photo 18', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/18.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xOC5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODc2MywiZXhwIjoxODEzMDY0NzYzfQ.WtT6DCupgLzFFWLRqvunQ2AWoHnL5lyQ1R2vbqBn-1g', false, 17),
('project-18', 'photo-19', 'photo 19', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/19.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8xOS5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODc3NCwiZXhwIjoxODEzMDY0Nzc0fQ.zQfLNskbaIteOERMjr8Ff9LgXwK7s0EYeV6Jv5n46ng', false, 18),
('project-19', 'photo-20', 'photo 20', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/20.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8yMC5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODc4NywiZXhwIjoxODEzMDY0Nzg3fQ.VLEv-7fIdNesk1o0sfXhKD4WHh29tIeENnRPfL1Z2x4', false, 19),
('project-20', 'photo-21', 'photo 21', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/21.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8yMS5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODc5OCwiZXhwIjoxODEzMDY0Nzk4fQ.EZuJoulEqTrw132ynOZxhomCxnlVQbtebb49toLzaY8', false, 20),
('project-21', 'photo-22', 'photo 22', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/22.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8yMi5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODgwNywiZXhwIjoxODEzMDY0ODA3fQ.X_FgwLigJqy7H3S99ju_dDtp4fEkmOD5WHCtog89Ri8', false, 21),
('project-22', 'photo-23', 'photo 23', 'Paisaje', 'Paisaje del set compartido.', 'portrait', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/sign/photos-bucket/photos/23.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85YWU1MTA4MC1mNjZhLTQyZDAtOTA4Mi1kZDFhMGJjNWVmNTgiLCJhbGciOiJIUzI1NiJ9.eyJ3cmwiOiJwaG90b3MtYnVja2V0L3Bob3Rvcy8yMy5qcGVnIiwic2NvcGUiOiJkb3dubG9hZCIsImlhdCI6MTc4MTUyODgxNiwiZXhwIjoxODEzMDY0ODE2fQ.gfCWT1dNGJL8RzvYiuXgGYGDJ46LT_rZXkHPV2solfI', false, 22),
('project-23', 'photo-24', 'photo 24', 'Paisaje', 'Paisaje del set compartido.', 'landscape', 'https://liabsnxydrjwdgimkluy.supabase.co/storage/v1/object/public/photos-bucket/photos/2.jpg', false, 23);